language: go
go:
  - "1.11"

os:
  - linux
  - osx

dist: trusty
sudo: false

git:
  submodules: false

install: GO111MODULE=on go mod download
script:
  - GO111MODULE=on go test -coverprofile cover.profile -v ./...
