# Public Domain (-) 2018-present, The Peerbase Authors.
# See the Peerbase UNLICENSE file for details.

language: go
go:
  - "1.11"

os:
  - linux
  - osx

dist: trusty
sudo: false

git:
  quiet: true
  submodules: false

install: true
script:
  - ./environ/ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
